class SavePatientInsuranceResponse {
  int patientInsuranceId;
  int patientId;
  int practiceInsuranceCompanyId;
  String subscriberPrefix;
  String subscriberFirstName;
  String subscriberMiddleName;
  String subscriberLastName;
  String subscriberSuffix;
  String subscriberPrimaryPhone;
  String subscriberPrimaryPhoneType;
  String subscriberPrimaryPhoneExt;
  String subscriberSecondaryPhone;
  String subscriberSecondaryPhoneType;
  String subscriberSecondaryPhoneExt;
  dynamic subscriberDob;
  String subscriberGender;
  dynamic subscriberRelationshipToPatient;
  dynamic subscriberSsn;
  String subscriberAddress1;
  String subscriberAddress2;
  String subscriberCity;
  String subscriberState;
  String subscriberZip;
  String subscriberGroupPlanNumber;
  String subscriberMemberNumber;
  String networkType;
  String groupEmployerName;
  bool isPrimary;
  String deactivateInsuranceReason;
  bool isActive;
  bool isPolicyHolderSameAsPatient;
  bool isPolicyHolderAddressSameAsPatient;
  bool isVerified;
  dynamic verifiedDate;
  dynamic insuranceVerificationStatusId;
  String createdDate;
  String modifiedDate;
  String createdByUserId;
  String modifiedByUserId;
  dynamic nonOsreference;
  String practiceInsuranceCompanyName;
  dynamic practiceInsuranceCompanyDescription;
  dynamic practiceInsuranceCompanyCode;
  String practiceInsuranceCompanyAddress1;
  dynamic practiceInsuranceCompanyAddress2;
  dynamic practiceInsuranceCompanySuite;
  String practiceInsuranceCompanyCity;
  String practiceInsuranceCompanyState;
  String practiceInsuranceCompanyZipcode;
  String practiceInsuranceCompanyPhone;
  dynamic practiceInsuranceCompanyPhoneExt;
  dynamic practiceInsuranceCompanyPayorId;
  bool practiceInsuranceCompanyIsMedicaid;
  dynamic practiceInsuranceCompanyPlanType;
  int practiceId;
  dynamic lastPatientClaimId;

  SavePatientInsuranceResponse({
    required this.patientInsuranceId,
    required this.patientId,
    required this.practiceInsuranceCompanyId,
    required this.subscriberPrefix,
    required this.subscriberFirstName,
    required this.subscriberMiddleName,
    required this.subscriberLastName,
    required this.subscriberSuffix,
    required this.subscriberPrimaryPhone,
    required this.subscriberPrimaryPhoneType,
    required this.subscriberPrimaryPhoneExt,
    required this.subscriberSecondaryPhone,
    required this.subscriberSecondaryPhoneType,
    required this.subscriberSecondaryPhoneExt,
    required this.subscriberDob,
    required this.subscriberGender,
    required this.subscriberRelationshipToPatient,
    required this.subscriberSsn,
    required this.subscriberAddress1,
    required this.subscriberAddress2,
    required this.subscriberCity,
    required this.subscriberState,
    required this.subscriberZip,
    required this.subscriberGroupPlanNumber,
    required this.subscriberMemberNumber,
    required this.networkType,
    required this.groupEmployerName,
    required this.isPrimary,
    required this.deactivateInsuranceReason,
    required this.isActive,
    required this.isPolicyHolderSameAsPatient,
    required this.isPolicyHolderAddressSameAsPatient,
    required this.isVerified,
    required this.verifiedDate,
    this.insuranceVerificationStatusId,
    required this.createdDate,
    required this.modifiedDate,
    required this.createdByUserId,
    required this.modifiedByUserId,
    this.nonOsreference,
    required this.practiceInsuranceCompanyName,
    this.practiceInsuranceCompanyDescription,
    this.practiceInsuranceCompanyCode,
    required this.practiceInsuranceCompanyAddress1,
    required this.practiceInsuranceCompanyAddress2,
    required this.practiceInsuranceCompanySuite,
    required this.practiceInsuranceCompanyCity,
    required this.practiceInsuranceCompanyState,
    required this.practiceInsuranceCompanyZipcode,
    required this.practiceInsuranceCompanyPhone,
    this.practiceInsuranceCompanyPhoneExt,
    this.practiceInsuranceCompanyPayorId,
    required this.practiceInsuranceCompanyIsMedicaid,
    this.practiceInsuranceCompanyPlanType,
    required this.practiceId,
    this.lastPatientClaimId,
  });

  factory SavePatientInsuranceResponse.fromJson(Map<String, dynamic> json) => SavePatientInsuranceResponse(
    patientInsuranceId: json['patientInsuranceId'],
    patientId: json['patientId'],
    practiceInsuranceCompanyId: json['practiceInsuranceCompanyId'],
    subscriberPrefix: json['subscriberPrefix'],
    subscriberFirstName: json['subscriberFirstName'],
    subscriberMiddleName: json['subscriberMiddleName'],
    subscriberLastName: json['subscriberLastName'],
    subscriberSuffix: json['subscriberSuffix'],
    subscriberPrimaryPhone: json['subscriberPrimaryPhone'],
    subscriberPrimaryPhoneType: json['subscriberPrimaryPhoneType'],
    subscriberPrimaryPhoneExt: json['subscriberPrimaryPhoneExt'],
    subscriberSecondaryPhone: json['subscriberSecondaryPhone'],
    subscriberSecondaryPhoneType: json['subscriberSecondaryPhoneType'],
    subscriberSecondaryPhoneExt: json['subscriberSecondaryPhoneExt'],
    subscriberDob: json['subscriberDob'].toString(),
    subscriberGender: json['subscriberGender'],
    subscriberRelationshipToPatient: json['subscriberRelationshipToPatient'],
    subscriberSsn: json['subscriberSsn'],
    subscriberAddress1: json['subscriberAddress1'],
    subscriberAddress2: json['subscriberAddress2'],
    subscriberCity: json['subscriberCity'],
    subscriberState: json['subscriberState'],
    subscriberZip: json['subscriberZip'],
    subscriberGroupPlanNumber: json['subscriberGroupPlanNumber'],
    subscriberMemberNumber: json['subscriberMemberNumber'],
    networkType: json['networkType'],
    groupEmployerName: json['groupEmployerName'],
    isPrimary: json['isPrimary'],
    deactivateInsuranceReason: json['deactivateInsuranceReason'],
    isActive: json['isActive'],
    isPolicyHolderSameAsPatient: json['isPolicyHolderSameAsPatient'],
    isPolicyHolderAddressSameAsPatient: json['isPolicyHolderAddressSameAsPatient'],
    isVerified: json['isVerified'],
    verifiedDate: json['verifiedDate'].toString(),
    insuranceVerificationStatusId: json['insuranceVerificationStatusId'],
    createdDate: json['createdDate'].toString(),
    modifiedDate: json['modifiedDate'].toString(),
    createdByUserId: json['createdByUserId'],
    modifiedByUserId: json['modifiedByUserId'],
    nonOsreference: json['nonOsreference'],
    practiceInsuranceCompanyName: json['practiceInsuranceCompanyName'],
    practiceInsuranceCompanyDescription: json['practiceInsuranceCompanyDescription'],
    practiceInsuranceCompanyCode: json['practiceInsuranceCompanyCode'],
    practiceInsuranceCompanyAddress1: json['practiceInsuranceCompanyAddress1'],
    practiceInsuranceCompanyAddress2: json['practiceInsuranceCompanyAddress2'],
    practiceInsuranceCompanySuite: json['practiceInsuranceCompanySuite'],
    practiceInsuranceCompanyCity: json['practiceInsuranceCompanyCity'],
    practiceInsuranceCompanyState: json['practiceInsuranceCompanyState'],
    practiceInsuranceCompanyZipcode: json['practiceInsuranceCompanyZipcode'],
    practiceInsuranceCompanyPhone: json['practiceInsuranceCompanyPhone'],
    practiceInsuranceCompanyPhoneExt: json['practiceInsuranceCompanyPhoneExt'],
    practiceInsuranceCompanyPayorId: json['practiceInsuranceCompanyPayorId'],
    practiceInsuranceCompanyIsMedicaid: json['practiceInsuranceCompanyIsMedicaid'],
    practiceInsuranceCompanyPlanType: json['practiceInsuranceCompanyPlanType'],
    practiceId: json['practiceId'],
    lastPatientClaimId: json['lastPatientClaimId'],
  );

  Map<String, dynamic> toJson() => {
    'patientInsuranceId': patientInsuranceId,
    'patientId': patientId,
    'practiceInsuranceCompanyId': practiceInsuranceCompanyId,
    'subscriberPrefix': subscriberPrefix,
    'subscriberFirstName': subscriberFirstName,
    'subscriberMiddleName': subscriberMiddleName,
    'subscriberLastName': subscriberLastName,
    'subscriberSuffix': subscriberSuffix,
    'subscriberPrimaryPhone': subscriberPrimaryPhone,
    'subscriberPrimaryPhoneType': subscriberPrimaryPhoneType,
    'subscriberPrimaryPhoneExt': subscriberPrimaryPhoneExt,
    'subscriberSecondaryPhone': subscriberSecondaryPhone,
    'subscriberSecondaryPhoneType': subscriberSecondaryPhoneType,
    'subscriberSecondaryPhoneExt': subscriberSecondaryPhoneExt,
    'subscriberDob': subscriberDob.toString(),
    'subscriberGender': subscriberGender,
    'subscriberRelationshipToPatient': subscriberRelationshipToPatient,
    'subscriberSsn': subscriberSsn,
    'subscriberAddress1': subscriberAddress1,
    'subscriberAddress2': subscriberAddress2,
    'subscriberCity': subscriberCity,
    'subscriberState': subscriberState,
    'subscriberZip': subscriberZip,
    'subscriberGroupPlanNumber': subscriberGroupPlanNumber,
    'subscriberMemberNumber': subscriberMemberNumber,
    'networkType': networkType,
    'groupEmployerName': groupEmployerName,
    'isPrimary': isPrimary,
    'deactivateInsuranceReason': deactivateInsuranceReason,
    'isActive': isActive,
    'isPolicyHolderSameAsPatient': isPolicyHolderSameAsPatient,
    'isPolicyHolderAddressSameAsPatient': isPolicyHolderAddressSameAsPatient,
    'isVerified': isVerified,
    'verifiedDate': verifiedDate.toString(),
    'insuranceVerificationStatusId': insuranceVerificationStatusId,
    'createdDate': createdDate,
    'modifiedDate': modifiedDate,
    'createdByUserId': createdByUserId,
    'modifiedByUserId': modifiedByUserId,
    'nonOsreference': nonOsreference,
    'practiceInsuranceCompanyName': practiceInsuranceCompanyName,
    'practiceInsuranceCompanyDescription': practiceInsuranceCompanyDescription,
    'practiceInsuranceCompanyCode': practiceInsuranceCompanyCode,
    'practiceInsuranceCompanyAddress1': practiceInsuranceCompanyAddress1,
    'practiceInsuranceCompanyAddress2': practiceInsuranceCompanyAddress2,
    'practiceInsuranceCompanySuite': practiceInsuranceCompanySuite,
    'practiceInsuranceCompanyCity': practiceInsuranceCompanyCity,
    'practiceInsuranceCompanyState': practiceInsuranceCompanyState,
    'practiceInsuranceCompanyZipcode': practiceInsuranceCompanyZipcode,
    'practiceInsuranceCompanyPhone': practiceInsuranceCompanyPhone,
    'practiceInsuranceCompanyPhoneExt': practiceInsuranceCompanyPhoneExt,
    'practiceInsuranceCompanyPayorId': practiceInsuranceCompanyPayorId,
    'practiceInsuranceCompanyIsMedicaid': practiceInsuranceCompanyIsMedicaid,
    'practiceInsuranceCompanyPlanType': practiceInsuranceCompanyPlanType,
    'practiceId': practiceId,
    'lastPatientClaimId': lastPatientClaimId,
  };
}
