class SavePatientEmergencyContactDetailResponse {
  int patientId;
  String patientGuid;
  int practiceId;
  String practiceName;
  String patientPrefix;
  String patientFirstName;
  String patientMiddleName;
  String patientLastName;
  String patientName;
  String patientDisplayName;
  String? patientPreferredName;
  String? patientSuffixName;
  String patientGender;
  String patientMaritalStatus;
  int patientAge;
  String patientLanguagePreference;
  bool hasPrimaryDentist;
  int primaryDentistId;
  String patientPrimaryPhone;
  String patientPrimaryType;
  dynamic patientPrimaryPhoneExt;
  String patientPrimaryEmailAddress;
  String? patientSecondaryPhone;
  String? patientSecondaryPhoneType;
  dynamic patientSecondaryPhoneExt;
  dynamic patientSecondaryEmailAddress;
  dynamic patientAddress1;
  dynamic patientAddress2;
  dynamic patientCity;
  dynamic patientState;
  dynamic patientZip;
  String patientEmergencyContactFirstName;
  String patientEmergencyContactLastName;
  String patientEmergencyContactRelationship;
  String patientEmergencyContactFormattedDob;
  String patientEmergencyContactPhone;
  String patientEmergencyContactPhoneType;
  String patientEmergencyContactPhoneExt;
  bool isAssociatedPatient;
  String associatedPatientRelationship;
  bool isPatientAgreedToContactViaEmail;
  bool isPatientAgreedToContactViaText;
  bool isPatientAgreedToMedicalConditions;
  bool isPatientAgreedToPolicy;
  bool isPatientAgreedToPracticePolicies;
  String patientCreatedDate;
  dynamic providerLicenseNumber;
  dynamic providerNotes;
  dynamic providerNpi;
  String primaryDentistFirstName;
  String primaryDentistLastName;
  String primaryDentistName;
  dynamic primaryDentistContactNumber;
  String primaryDentistOfficeName;
  dynamic primaryDentistOfficeAddress;
  dynamic primaryDentistOfficeCity;
  dynamic primaryDentistOfficeState;
  dynamic primaryDentistOfficeZipcode;
  dynamic primaryDentistEmailAddress;
  dynamic primaryDentistPhoneNumber;
  String patientNotes;
  String patientStateAbbreviation;
  dynamic patientStatusId;
  int practiceLocationId;
  String practiceLocationName;
  dynamic patientHobbiesInterests;
  String patientStudentStatus;
  dynamic patientStatus;
  dynamic patientStatusDescription;
  bool isPatientFrp;
  String practicePrimaryLocationName;
  String practicePrimaryLocationAddress;
  String practicePrimaryLocationCity;
  String practicePrimaryLocationState;
  String practicePrimaryLocationStateAbbreviation;
  String practicePrimaryLocationZip;
  String patientFormattedDob;
  String patientDob;
  String patientEmergencyContactDob;
  int patientLocationId;
  String patientLocationName;
  String patientFormattedPrimaryPhone;
  dynamic patientFormattedSecondaryPhone;
  String patientFormattedEmergencyContactPhone;
  bool isPatientActive;
  bool isDdsnotOnFile;
  String ddsprimaryDentistName;
  dynamic nonOsreference;

  SavePatientEmergencyContactDetailResponse({
    required this.patientId,
    required this.patientGuid,
    required this.practiceId,
    required this.practiceName,
    required this.patientPrefix,
    required this.patientFirstName,
    required this.patientMiddleName,
    required this.patientLastName,
    required this.patientName,
    required this.patientDisplayName,
    required this.patientPreferredName,
    required this.patientSuffixName,
    required this.patientGender,
    required this.patientMaritalStatus,
    required this.patientAge,
    required this.patientLanguagePreference,
    required this.hasPrimaryDentist,
    required this.primaryDentistId,
    required this.patientPrimaryPhone,
    required this.patientPrimaryType,
    required this.patientPrimaryPhoneExt,
    required this.patientPrimaryEmailAddress,
    required this.patientSecondaryPhone,
    required this.patientSecondaryPhoneType,
    required this.patientSecondaryPhoneExt,
    required this.patientSecondaryEmailAddress,
    required this.patientAddress1,
    required this.patientAddress2,
    required this.patientCity,
    required this.patientState,
    required this.patientZip,
    required this.patientEmergencyContactFirstName,
    required this.patientEmergencyContactLastName,
    required this.patientEmergencyContactRelationship,
    required this.patientEmergencyContactFormattedDob,
    required this.patientEmergencyContactPhone,
    required this.patientEmergencyContactPhoneType,
    required this.patientEmergencyContactPhoneExt,
    required this.isAssociatedPatient,
    required this.associatedPatientRelationship,
    required this.isPatientAgreedToContactViaEmail,
    required this.isPatientAgreedToContactViaText,
    required this.isPatientAgreedToMedicalConditions,
    required this.isPatientAgreedToPolicy,
    required this.isPatientAgreedToPracticePolicies,
    required this.patientCreatedDate,
    required this.providerLicenseNumber,
    required this.providerNotes,
    required this.providerNpi,
    required this.primaryDentistFirstName,
    required this.primaryDentistLastName,
    required this.primaryDentistName,
    required this.primaryDentistContactNumber,
    required this.primaryDentistOfficeName,
    required this.primaryDentistOfficeAddress,
    required this.primaryDentistOfficeCity,
    required this.primaryDentistOfficeState,
    required this.primaryDentistOfficeZipcode,
    required this.primaryDentistEmailAddress,
    required this.primaryDentistPhoneNumber,
    required this.patientNotes,
    required this.patientStateAbbreviation,
    required this.patientStatusId,
    required this.practiceLocationId,
    required this.practiceLocationName,
    required this.patientHobbiesInterests,
    required this.patientStudentStatus,
    required this.patientStatus,
    required this.patientStatusDescription,
    required this.isPatientFrp,
    required this.practicePrimaryLocationName,
    required this.practicePrimaryLocationAddress,
    required this.practicePrimaryLocationCity,
    required this.practicePrimaryLocationState,
    required this.practicePrimaryLocationStateAbbreviation,
    required this.practicePrimaryLocationZip,
    required this.patientFormattedDob,
    required this.patientDob,
    required this.patientEmergencyContactDob,
    required this.patientLocationId,
    required this.patientLocationName,
    required this.patientFormattedPrimaryPhone,
    required this.patientFormattedSecondaryPhone,
    required this.patientFormattedEmergencyContactPhone,
    required this.isPatientActive,
    required this.isDdsnotOnFile,
    required this.ddsprimaryDentistName,
    required this.nonOsreference,
  });

  factory SavePatientEmergencyContactDetailResponse.fromJson(Map<String, dynamic> json) =>
      SavePatientEmergencyContactDetailResponse(
    patientId: json['patientId'],
    patientGuid: json['patientGuid'],
    practiceId: json['practiceId'],
    practiceName: json['practiceName'],
    patientPrefix: json['patientPrefix'],
    patientFirstName: json['patientFirstName'],
    patientMiddleName: json['patientMiddleName'],
    patientLastName: json['patientLastName'],
    patientName: json['patientName'],
    patientDisplayName: json['patientDisplayName'],
    patientPreferredName: json['patientPreferredName'],
    patientSuffixName: json['patientSuffixName'],
    patientGender: json['patientGender'],
    patientMaritalStatus: json['patientMaritalStatus'],
    patientAge: json['patientAge'],
    patientLanguagePreference: json['patientLanguagePreference'],
    hasPrimaryDentist: json['hasPrimaryDentist'],
    primaryDentistId: json['primaryDentistId'],
    patientPrimaryPhone: json['patientPrimaryPhone'],
    patientPrimaryType: json['patientPrimaryType'],
    patientPrimaryPhoneExt: json['patientPrimaryPhoneExt'],
    patientPrimaryEmailAddress: json['patientPrimaryEmailAddress'],
    patientSecondaryPhone: json['patientSecondaryPhone'],
    patientSecondaryPhoneType: json['patientSecondaryPhoneType'],
    patientSecondaryPhoneExt: json['patientSecondaryPhoneExt'],
    patientSecondaryEmailAddress: json['patientSecondaryEmailAddress'],
    patientAddress1: json['patientAddress1'],
    patientAddress2: json['patientAddress2'],
    patientCity: json['patientCity'],
    patientState: json['patientState'],
    patientZip: json['patientZip'],
    patientEmergencyContactFirstName: json['patientEmergencyContactFirstName'],
    patientEmergencyContactLastName: json['patientEmergencyContactLastName'],
    patientEmergencyContactRelationship: json['patientEmergencyContactRelationship'],
    patientEmergencyContactFormattedDob: json['patientEmergencyContactFormattedDob'],
    patientEmergencyContactPhone: json['patientEmergencyContactPhone'],
    patientEmergencyContactPhoneType: json['patientEmergencyContactPhoneType'],
    patientEmergencyContactPhoneExt: json['patientEmergencyContactPhoneExt'],
    isAssociatedPatient: json['isAssociatedPatient'],
    associatedPatientRelationship: json['associatedPatientRelationship'],
    isPatientAgreedToContactViaEmail: json['isPatientAgreedToContactViaEmail'],
    isPatientAgreedToContactViaText: json['isPatientAgreedToContactViaText'],
    isPatientAgreedToMedicalConditions: json['isPatientAgreedToMedicalConditions'],
    isPatientAgreedToPolicy: json['isPatientAgreedToPolicy'],
    isPatientAgreedToPracticePolicies: json['isPatientAgreedToPracticePolicies'],
    patientCreatedDate: json['patientCreatedDate'],
    providerLicenseNumber: json['providerLicenseNumber'],
    providerNotes: json['providerNotes'],
    providerNpi: json['providerNpi'],
    primaryDentistFirstName: json['primaryDentistFirstName'],
    primaryDentistLastName: json['primaryDentistLastName'],
    primaryDentistName: json['primaryDentistName'],
    primaryDentistContactNumber: json['primaryDentistContactNumber'],
    primaryDentistOfficeName: json['primaryDentistOfficeName'],
    primaryDentistOfficeAddress: json['primaryDentistOfficeAddress'],
    primaryDentistOfficeCity: json['primaryDentistOfficeCity'],
    primaryDentistOfficeState: json['primaryDentistOfficeState'],
    primaryDentistOfficeZipcode: json['primaryDentistOfficeZipcode'],
    primaryDentistEmailAddress: json['primaryDentistEmailAddress'],
    primaryDentistPhoneNumber: json['primaryDentistPhoneNumber'],
    patientNotes: json['patientNotes'],
    patientStateAbbreviation: json['patientStateAbbreviation'],
    patientStatusId: json['patientStatusId'],
    practiceLocationId: json['practiceLocationId'],
    practiceLocationName: json['practiceLocationName'],
    patientHobbiesInterests: json['patientHobbiesInterests'],
    patientStudentStatus: json['patientStudentStatus'],
    patientStatus: json['patientStatus'],
    patientStatusDescription: json['patientStatusDescription'],
    isPatientFrp: json['isPatientFrp'],
    practicePrimaryLocationName: json['practicePrimaryLocationName'],
    practicePrimaryLocationAddress: json['practicePrimaryLocationAddress'],
    practicePrimaryLocationCity: json['practicePrimaryLocationCity'],
    practicePrimaryLocationState: json['practicePrimaryLocationState'],
    practicePrimaryLocationStateAbbreviation: json['practicePrimaryLocationStateAbbreviation'],
    practicePrimaryLocationZip: json['practicePrimaryLocationZip'],
    patientFormattedDob: json['patientFormattedDob'],
    patientDob: json['patientDob'],
    patientEmergencyContactDob: json['patientEmergencyContactDob'],
    patientLocationId: json['patientLocationId'],
    patientLocationName: json['patientLocationName'],
    patientFormattedPrimaryPhone: json['patientFormattedPrimaryPhone'],
    patientFormattedSecondaryPhone: json['patientFormattedSecondaryPhone'],
    patientFormattedEmergencyContactPhone: json['patientFormattedEmergencyContactPhone'],
    isPatientActive: json['isPatientActive'],
    isDdsnotOnFile: json['isDdsnotOnFile'],
    ddsprimaryDentistName: json['ddsprimaryDentistName'],
    nonOsreference: json['nonOsreference'],
  );
}
